### ISSUE TITLE
open /usr/lib/go-1.19/src/syscall/rlimit.go: no such file or directory

### ISSUE THREAD

**Issue by themoonisacheese** [hajimehoshi/hitsumabushi#23]
On the latest commit, the title message appears when running example/helloworld/run.sh.
/usr/lib/go-1.19/src/syscall/ has indeed no file named rlimit.go, but it can be found in /usr/share/go-1.19/src/os/rlimit.go.

worth noting i am using amd64 (not trying to run just yet, i'd prefer compiling outside a VM)
Config:
debian 12 up to date
golang-1.19-go/stable,now 1.19.8-2 amd64

full output:
```shell
❯ ./run.sh
open /usr/lib/go-1.19/src/syscall/rlimit.go: no such file or directory
exit status 1
```

**Comment by hajimehoshi** [comment]
Try Go 1.19.12.

See also https://github.com/hajimehoshi/hitsumabushi/issues/22
